### ISSUE TITLE
self.stopTemperature

### ISSUE THREAD

**Issue by PeterBBCUser** [dumbo25/rpi-fan#1]
Looking at the code the fan is suppose to stop when the self.stopTemperature is reached, but It's never checked against anything it looks like the scrip only turn the fan on when it get to the max temp and runs till the sleep time has run out (30sec) then stops again.

**Comment by dumbo25** [comment]
Try changing the temperatures and you will see it turns on and off.

If the temp is too high or too low then it may stay on for the full 30
seconds, or never turn on or never turn off. 60 degrees celsius - 5 degrees
seems to work well for me. But, I have tried other temps.

Once on, it won't shut off for 30 seconds even if the temp is below the
stop temp. This is to prevent the fan from cycling on and off.

I hope this helps.

Jeff

**Comment by PeterBBCUser** [comment]
if you change the off temperature on line 159 "self.stopTemperature = self.startTemperature - 5.0"
It still only runs for 30 sec and I don't see anywhere in the code where this variable (self.stopTemperature) gets used apart for outputting it to the log file.
I have my on temp. set to 45 and the off to -10 and it still switches off after 30 sec and only comes back on when it reaches the 45 deg.
Or am I missing something as to where the self.stopTemperature gets used then?
Peter.

**Comment by dumbo25** [comment]
Peter,

Please check out the instructable comments, where someone had a similar
issue and submitted changed code.

The code as it is works fine for my purposes. In the comments of the
instructables, I attempt to explain certain features of the code. For
example, why 45 is too low of a setting. I am surprised that at 45 and -10
it shuts off at all. If the CPU is doing anything significant, I would
expect the fan to un continuously with those settings.

Here is a link to the instructable:
https://www.instructables.com/id/Control-a-Cooling-Fan-on-a-Raspberry-Pi-3/

Thanks.
Jeff

**Comment by PeterBBCUser** [comment]
That's my point it does not run continuously it stops after the 30sec sleep timer, I am no python programmer but when I look at your code I don't see where self.stopTemperature is used apart from it being outputted to the log but not actually used in the code to control when the fan is turned off.
O and I am running Deluge torrent server and it's on the new Pi 3B+ (with heat-sink) if I turn the fan on continuously I get a temperate of  : -
CPU Temp: 34.3 C
GPU Temp: 34.3 C
with the fan off it runs up to : -
CPU Temp: 65.5 C
GPU Temp: 65.5 C 
So guess the new Pi 3B+ runs cooler than older models.
Will look at the modified code from your link and see if that works any better in regards to the cut off temperature.

Thanks
Peter.

**Comment by PeterBBCUser** [comment]
This is added in at line 176 : -
                if self.cpuTemperature > self.stopTemperature:
                    # need to turn fan on, but only if the fan is off
                    if not myFan.fanOff:
                        myFan.setFan(self.cpuTemperature, True, myPin)

And a couple of other changes like the sleep time to 1 sec and setting self.stopTemperature = 40.0 to the temperature you want to stop the fan but it also does not work as expected. runs for a bit then stops before it has come anywhere near the 40 deg like at about 49 deg.

**Comment by PeterBBCUser** [comment]
the one [http://siriuspal.com/raspberry-pi-fan-control](hear) does exactly what I was after, its very simple but works as expected.

**Comment by dumbo25** [comment]
Sorry, you were right. I changed the code. Thanks. Jeff
